### ISSUE TITLE
Error when running service update on worker node

### ISSUE THREAD

**Issue by flopon** [docupdater/docupdater#1]
Hi,

Thanks for your hard work ! Your proposed solution almost fit all my needs ;)

I am doing some test, so I will report back here.

Here an exception raised when trying to update service on a worker node. In this case, container is deployed to update standalone containers on a worker node, so --disable-services-check can be used, but I think it's preferable to catch the exception.

```
2019-02-26 10:31:24 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2019-02-26 10:31:24 UTC], next run at: 2019-02-26 10:31:24 UTC)" raised an exception,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status,
    response.raise_for_status(),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status,
    raise HTTPError(http_error_msg, response=self),
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http+docker://localhost/v1.35/services,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job,
    retval = job.func(*job.args, **job.kwargs),
  File "/usr/local/lib/python3.7/site-packages/docupdater/lib/scanner.py", line 68, in update,
    monitoreds = self.scan_monitored(),
  File "/usr/local/lib/python3.7/site-packages/docupdater/lib/scanner.py", line 63, in scan_monitored,
    raise e,
  File "/usr/local/lib/python3.7/site-packages/docupdater/lib/scanner.py", line 59, in scan_monitored,
    monitored.extend(self._scan_services()),
  File "/usr/local/lib/python3.7/site-packages/docupdater/lib/scanner.py", line 40, in _scan_services,
    for service in self.client.services.list():,
  File "/usr/local/lib/python3.7/site-packages/docker/models/services.py", line 267, in list,
    for s in self.client.api.services(**kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 34, in wrapper,
    return f(self, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/api/service.py", line 280, in services,
    return self._result(self._get(url, params=params), True),
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 262, in _result,
    self._raise_for_status(response),
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status,
    raise create_api_error_from_http_exception(e),
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception,
    raise cls(e, response=response, explanation=explanation),
docker.errors.APIError: 503 Server Error: Service Unavailable ("This node is not a swarm manager. Worker nodes can't be used to view or modify cluster state. Please run this command on a manager node or promote the current node to a manager."),
```

**Comment by mathcantin** [comment]
Hi,
Thanks you for your interest. There are currently several bugs in the project. I will release the first stable version today or tomorrow.

**Comment by mathcantin** [comment]
@flopon I update documentation and I added a check on the boot for that. That now in master branch.
