### ISSUE TITLE
Issue with private repo

### ISSUE THREAD

**Issue by EugeneKallis** [docupdater/docupdater#17]
Im having an issue when starting with REPO_USER and REPO_PASS set.

```
docker run -d --name docupdater \
  -e REPO_USER=<username>-e REPO_PASS=<password>\
  -v /var/run/docker.sock:/var/run/docker.sock \
  docupdater/docupdater
```

Log:
```
2019-03-07 15:09:50 : INFO : docupdater : Version: 0.5.1-master
Traceback (most recent call last):
  File "/usr/local/bin/entrypoint", line 7, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/docupdater/docupdater.py", line 179, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docupdater/docupdater.py", line 114, in cli
    config.config_blacklist()  # Configure mask on logger
  File "/usr/local/lib/python3.7/site-packages/docupdater/lib/config.py", line 115, in config_blacklist
    handler.addFilter(BlacklistFilter(set(self.filtered_strings)))
TypeError: unhashable type: 'dict'
```

**Comment by EugeneKallis** [comment]
Fixed in 0.5.2
